import Link from "next/link";
import { ArrowUpRight, ArrowDown, Circle } from "lucide-react";
import { Logo } from "@/app/components/Logo";
import { LandingMotion } from "@/app/components/LandingMotion";
import { SCRIP_WATERFALL_ADDRESS, CONFIDENTIAL_USDC_ADDRESS, WATERFALL_SPLIT_ADDRESS } from "@/app/lib/contracts";

const steps = [
  ["01", "Keep 0xSplits intact", "Revenue follows the existing, unmodified 0xSplits rail. Its public total and composability remain exactly where integrators expect them.", "Unmodified protocol"],
  ["02", "Seal the waterfall", "Recoup caps, split ratios, and milestone gates are encrypted in the browser — the deal terms, not just a single percentage.", "Nox privacy layer"],
  ["03", "Compute, then settle", "Nox evaluates the sealed waterfall against the public total inside the TEE and settles confidential cUSDC. Auditors see a batch only when explicitly granted access.", "Confidential computation"],
];
const contracts = [["Scrip waterfall", SCRIP_WATERFALL_ADDRESS], ["Confidential USDC", CONFIDENTIAL_USDC_ADDRESS], ["0xSplits rail", WATERFALL_SPLIT_ADDRESS]] as const;
const faqs = [
  ["What exactly is sealed, and what isn't?", "Every tier's recoup cap, split ratio, and milestone gate, plus every individual payout, are sealed. Owner addresses, tier count and order, and the total revenue distributed are public — Scrip hides the deal terms and who earns what, not that a deal exists."],
  ["Is this really computed confidentially, or just hidden in the UI?", "Computed. Two waterfalls on Sepolia with identical tiers, funded with the same 1 USDC, differ only in one sealed milestone bit — and decrypt to different payouts (0.629999/0.369998 USDC vs. 0.765/0.235 USDC). See the money shot above; the transaction hashes are public."],
  ["Does Scrip modify 0xSplits?", "No. 0xSplits routes revenue exactly as it already does — Scrip is just a normal recipient of an unmodified Split. The confidential layer only starts once funds reach Scrip's own contract."],
  ["Can the founder see everyone's payout?", "No. Each owner decrypts only their own payout. The founder sets the sealed terms but doesn't get a standing view of the computed results — an auditor can be granted that scoped view explicitly, on-chain, revocably."],
  ["What happens if a milestone isn't met?", "The tiers gated to that milestone simply compute to zero for this distribution — the rest of the waterfall (recoup caps, ungated splits) still runs normally. Nothing reverts and nothing leaks about why."],
  ["Is this real money, or a simulation?", "Real Sepolia USDC, wrapped 1:1 into a real ERC-7984 confidential token, moved through a real, unmodified 0xSplits Split. No mock data anywhere on the core path."],
  ["Why Nox instead of FHE?", "Nox is iExec's TEE-based confidential compute layer — sealed arithmetic (add/sub/mul/div, comparisons, and conditional select) runs as normal, synchronous Solidity calls inside a trusted execution environment. This build uses Nox only; no FHE anywhere."],
] as const;
const Arrow = () => <ArrowUpRight size={15} aria-hidden />;

export default function Landing() {
  return <LandingMotion><div className="site-shell">
    <header className="site-header"><Link href="/" aria-label="Scrip home"><Logo /></Link><nav className="desktop-nav"><a href="#wrap">The wrap</a><a href="#comparison">Privacy</a><a href="#infrastructure">Deployment</a><Link href="/docs">Docs</Link></nav><Link className="button button-small button-outline" href="/app">Open Scrip <Arrow /></Link></header>
    <main>
      <section className="hero" id="product">
        <div className="hero-grid" aria-hidden><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-core"><span>§</span></div><span className="orbit-label label-a">0xSPLITS</span><span className="orbit-label label-b">NOX</span><span className="orbit-label label-c">cUSDC</span></div>
        <div className="hero-copy"><div className="eyebrow reveal">An unmodified protocol. A confidential deal.</div><h1 className="reveal">Pay your owners.<br/>Prove the total.<br/>Hide who gets what.</h1><p className="hero-lede reveal">Scrip runs a real conditional revenue deal on-chain — recoup caps, split ratios, and milestone gates sealed in a Nox TEE, wrapping the real 0xSplits rail unmodified. The total stays public and provable; the terms and every payout do not.</p><div className="hero-actions reveal"><Link href="/app" className="button button-primary">Launch the Sepolia app <Arrow /></Link><a href="#wrap" className="text-link">See the integration <ArrowDown size={14} aria-hidden /></a></div></div>
        <div className="hero-foot reveal"><span>Unmodified 0xSplits</span><i/><span>Nox sealed compute</span><i/><span>Live on Sepolia</span></div>
      </section>

      <section className="who-band"><p className="who-line reveal">For a startup and its investor, a royalty deal, or a profit-share agreement: real deal terms — who recoups first, how the rest splits, what a milestone changes — are commercially sensitive. On-chain today, you either publish them or stay off-chain. Scrip proves the distribution happened without publishing the deal.</p></section>

      <section className="statement section-pad" id="wrap"><div className="section-kicker reveal"><span>01</span> The composable privacy layer</div><div className="statement-grid"><h2 className="display-copy reveal">The protocol routes.<br/>Scrip seals.</h2><div className="statement-body reveal"><p>0xSplits still does its normal job: route revenue through a proven open-source protocol and leave a verifiable public total.</p><p>Scrip adds privacy after that boundary. Nox evaluates a sealed waterfall — recoup caps, split ratios, milestone gates — against the public total, then confidential ERC-7984 settlement gives each owner an isolated view—without a fork or modification to 0xSplits.</p></div></div></section>

      <section className="comparison section-pad" id="comparison"><div className="section-heading reveal"><div className="section-kicker"><span>02</span> Before and after</div><h2>Same rail.<br/>Smaller leak.</h2></div><p className="comparison-stakes reveal">On a standard public split, your cap table is exposed: competitors see your ownership structure, every contributor sees what every other contributor earns, and acquirers see your equity breakdown before you ever negotiate. Scrip keeps the total provable and seals the rest.</p><div className="comparison-grid">
        <article className="comparison-card before reveal"><span className="card-tag">Standard public split · illustrative example</span><h3>Everything becomes observable.</h3><div className="leak-flow"><b>3.00 USDC total</b><i/><span>60% → 1.80 USDC</span><span>40% → 1.20 USDC</span></div><ul><li>Distribution total: public</li><li>Ownership percentages: public</li><li>Individual payouts: public</li></ul></article>
        <article className="comparison-card after reveal"><span className="card-tag">0xSplits through Scrip · illustrative example</span><h3>Proof remains. Exposure does not.</h3><div className="leak-flow"><b>3.00 USDC total</b><i/><span>sealed terms → confidential cUSDC</span><span>sealed terms → confidential cUSDC</span></div><ul><li>Distribution total: public and provable</li><li>Deal terms (caps, ratios, milestones): sealed by Nox</li><li>Individual payouts: wallet-private</li></ul></article>
      </div><p className="comparison-note reveal">No protocol fork. No private replacement rail. Privacy is added at the allocation and settlement boundary.</p></section>

      <section className="workflow section-pad" id="how-it-works"><div className="section-heading reveal"><div className="section-kicker"><span>03</span> How the wrap works</div><h2>Composable in.<br/>Confidential out.</h2></div><div className="step-grid">{steps.map(([number,title,copy,tag]) => <article className="step-card reveal" key={number}><div className="step-top"><span>{number}</span><i/></div><div className={`step-visual visual-${number}`}><span className="visual-dot"/><span className="visual-line"/><span className="visual-lock">§</span></div><span className="card-tag">{tag}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>

      <section className="comparison section-pad" id="proof"><div className="section-heading reveal"><div className="section-kicker"><span>03b</span> The money shot</div><h2>Same total.<br/>Different deal.</h2></div><p className="comparison-stakes reveal">Every other confidential-split project seals a static number. Scrip seals a rule. Real, on Sepolia: two waterfalls, identical structure, funded with the same 2 USDC — the only difference is one sealed milestone bit.</p><div className="comparison-grid">
        <article className="comparison-card before reveal"><span className="card-tag">Waterfall #1 · milestone NOT met (real, decrypted)</span><h3>Founder 70% / investor 30% of the remainder.</h3><div className="leak-flow"><b>1.00 USDC total</b><i/><span>founder → 0.629999 USDC</span><span>investor → 0.369998 USDC</span></div><ul><li>Same tiers, same order, same amounts</li><li>Sealed milestone bit: not met</li></ul></article>
        <article className="comparison-card after reveal"><span className="card-tag">Waterfall #2 · milestone MET (real, decrypted)</span><h3>Founder 85% / investor 15% of the remainder.</h3><div className="leak-flow"><b>1.00 USDC total</b><i/><span>founder → 0.765 USDC</span><span>investor → 0.235 USDC</span></div><ul><li>Identical tiers, identical order, identical amounts</li><li>Sealed milestone bit: met</li></ul></article>
      </div><p className="comparison-note reveal">Nobody watching the chain — or these two contracts — can tell why the split differs. That&apos;s confidential computation, not confidential storage.</p></section>

      <section className="boundary section-pad"><div className="boundary-copy reveal"><div className="section-kicker"><span>04</span> The privacy boundary</div><h2>Confidential,<br/>not opaque.</h2><p>Scrip preserves the public facts required for trust while restricting financial details to the wallets entitled to see them.</p></div><div className="boundary-panel reveal"><div className="boundary-row"><div><span className="status sealed"><Circle size={9} fill="currentColor" stroke="none" /></span><h3>Sealed</h3></div><ul><li>Recoup caps, split ratios, milestone gates</li><li>Individual payout amounts</li><li>The waterfall evaluation itself</li></ul></div><div className="boundary-row"><div><span className="status public"><Circle size={9} fill="currentColor" stroke="none" /></span><h3>Public</h3></div><ul><li>Owner wallet addresses</li><li>Distribution activity</li><li>Total revenue distributed</li></ul></div><p className="boundary-note">Owners decrypt only their balance. Auditors receive scoped access only when a founder grants it on-chain.</p></div></section>

      <section className="infrastructure section-pad" id="infrastructure"><div className="section-heading reveal"><div className="section-kicker"><span>05</span> Deployable today</div><h2>Real contracts.<br/>Real settlement.</h2></div><div className="infra-grid"><article className="infra-main reveal"><span className="infra-index">Nox / TEE</span><h3>Confidential computation without sacrificing composability</h3><p>Encrypted allocations are processed inside a trusted execution environment while the surrounding Ethereum and 0xSplits interfaces remain familiar.</p><div className="enclave-diagram"><i/><span>sealed compute</span><i/></div></article><div className="infra-stack"><article className="infra-card reveal"><span>0xSplits</span><h3>Unmodified revenue routing</h3><p>The established open-source protocol remains untouched and supplies the publicly verifiable distribution total.</p></article><article className="infra-card reveal"><span>ERC-7984</span><h3>Confidential settlement</h3><p>Live Sepolia contracts settle encrypted cUSDC balances with owner-only decryption and scoped auditor access.</p></article></div></div><div className="contract-strip reveal"><span className="contract-title">Live on Sepolia</span>{contracts.map(([name,address]) => <a key={name} href={`https://sepolia.etherscan.io/address/${address}`} target="_blank" rel="noreferrer"><span>{name}</span><code>{address.slice(0,6)}…{address.slice(-4)}</code><Arrow /></a>)}</div></section>

      <section className="faq-section section-pad" id="faq"><div className="section-heading reveal"><div className="section-kicker"><span>07</span> FAQ</div><h2>Questions,<br/>answered plainly.</h2></div><div className="faq-list reveal">{faqs.map(([q, a]) => <details key={q} className="faq-item"><summary>{q}</summary><p>{a}</p></details>)}</div></section>

      <section className="final-cta section-pad"><div className="cta-orb" aria-hidden><span>§</span></div><div className="reveal"><div className="section-kicker"><span>06</span> Test the live wrap</div><h2>Public proof.<br/>Private outcomes.</h2><p>Build a sealed waterfall, send revenue through the unmodified 0xSplits rail, and watch Nox settle confidential payouts on Sepolia.</p><Link href="/app" className="button button-primary">Open Scrip <Arrow /></Link></div></section>
    </main>
    <footer className="site-footer"><div className="footer-brand"><Logo/><p>A confidential conditional-distribution layer for unmodified 0xSplits revenue flows.</p><span>Ethereum · 0xSplits · Nox</span></div><div className="footer-column"><strong>Product</strong><a href="#wrap">The wrap</a><a href="#proof">The proof</a><Link href="/app">Live app</Link></div><div className="footer-column"><strong>Proof</strong><a href="https://github.com/TheWeirdDee/scrip" target="_blank" rel="noreferrer">Source code <ArrowUpRight size={12} aria-hidden /></a><a href={`https://sepolia.etherscan.io/address/${SCRIP_WATERFALL_ADDRESS}`} target="_blank" rel="noreferrer">Sepolia contracts <ArrowUpRight size={12} aria-hidden /></a></div><div className="footer-bottom"><span>© 2026 Scrip</span><span>Unmodified rail. Confidential settlement.</span></div></footer>
  </div></LandingMotion>;
}