import Link from "next/link";
import { Logo } from "@/app/components/Logo";
import { LandingMotion } from "@/app/components/LandingMotion";
import { SCRIP_DISTRIBUTOR_ADDRESS, CONFIDENTIAL_USDC_ADDRESS, SPLIT_ADDRESS } from "@/app/lib/contracts";

const steps = [
  ["01", "Define ownership", "Create an ownership schedule in the browser. Wallets remain visible; every allocation is encrypted before it reaches the network.", "Private input"],
  ["02", "Route revenue", "Revenue moves through an unmodified 0xSplits Split, preserving a public record of the total entering each distribution.", "Public proof"],
  ["03", "Distribute privately", "Nox computes proportional payouts inside a trusted execution environment. Each owner can reveal only their own balance.", "Selective access"],
];
const contracts = [["Scrip distributor", SCRIP_DISTRIBUTOR_ADDRESS], ["Confidential USDC", CONFIDENTIAL_USDC_ADDRESS], ["0xSplits rail", SPLIT_ADDRESS]] as const;
const Arrow = () => <span aria-hidden>↗</span>;

export default function Landing() {
  return <LandingMotion><div className="site-shell">
    <header className="site-header"><Link href="/" aria-label="Scrip home"><Logo /></Link><nav className="desktop-nav"><a href="#product">Product</a><a href="#privacy">Privacy</a><a href="#infrastructure">Infrastructure</a></nav><Link className="button button-small button-outline" href="/app">Open Scrip <Arrow /></Link></header>
    <main>
      <section className="hero" id="product">
        <div className="hero-grid" aria-hidden><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-core"><span>§</span></div><span className="orbit-label label-a">OWNERSHIP</span><span className="orbit-label label-b">REVENUE</span><span className="orbit-label label-c">PAYOUT</span></div>
        <div className="hero-copy"><div className="eyebrow reveal">Confidential ownership infrastructure</div><h1 className="reveal">The private layer<br/>for shared value.</h1><p className="hero-lede reveal">Scrip gives companies and on-chain organizations a private cap table that distributes revenue—without exposing who owns how much or what they earn.</p><div className="hero-actions reveal"><Link href="/app" className="button button-primary">Launch app <Arrow /></Link><a href="#how-it-works" className="text-link">See how it works <span>↓</span></a></div></div>
        <div className="hero-foot reveal"><span>Built on Ethereum</span><i/><span>Powered by Nox</span><i/><span>Integrated with 0xSplits</span></div>
      </section>
      <section className="statement section-pad" id="privacy"><div className="section-kicker reveal"><span>01</span> The missing layer</div><div className="statement-grid"><h2 className="display-copy reveal">Ownership belongs<br/>on-chain. Exposure<br/>doesn&apos;t.</h2><div className="statement-body reveal"><p>Public ledgers make financial coordination verifiable. They also make every allocation and payout visible by default.</p><p>Scrip separates accountability from disclosure: the distribution total remains provable, while the cap table and individual earnings stay confidential.</p></div></div></section>
      <section className="workflow section-pad" id="how-it-works"><div className="section-heading reveal"><div className="section-kicker"><span>02</span> How it works</div><h2>Private by design.<br/>Clear by default.</h2></div><div className="step-grid">{steps.map(([number,title,copy,tag]) => <article className="step-card reveal" key={number}><div className="step-top"><span>{number}</span><i/></div><div className={`step-visual visual-${number}`}><span className="visual-dot"/><span className="visual-line"/><span className="visual-lock">§</span></div><span className="card-tag">{tag}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
      <section className="boundary section-pad"><div className="boundary-copy reveal"><div className="section-kicker"><span>03</span> The privacy boundary</div><h2>Confidential,<br/>not opaque.</h2><p>Scrip reveals enough to establish trust—never enough to expose an owner.</p></div><div className="boundary-panel reveal"><div className="boundary-row"><div><span className="status sealed">●</span><h3>Sealed</h3></div><ul><li>Ownership percentages</li><li>Individual payout amounts</li><li>Allocation computation</li></ul></div><div className="boundary-row"><div><span className="status public">●</span><h3>Public</h3></div><ul><li>Owner wallet addresses</li><li>Distribution activity</li><li>Total revenue distributed</li></ul></div><p className="boundary-note">Owners decide what they reveal. Auditors receive scoped access only when granted.</p></div></section>
      <section className="infrastructure section-pad" id="infrastructure"><div className="section-heading reveal"><div className="section-kicker"><span>04</span> Infrastructure</div><h2>Purpose-built from<br/>proven rails.</h2></div><div className="infra-grid"><article className="infra-main reveal"><span className="infra-index">Nox / TEE</span><h3>Confidential computation</h3><p>Encrypted allocations are processed inside a trusted execution environment, never exposed to the public chain.</p><div className="enclave-diagram"><i/><span>sealed compute</span><i/></div></article><div className="infra-stack"><article className="infra-card reveal"><span>0xSplits</span><h3>Revenue routing</h3><p>The established protocol remains untouched and provides the publicly verifiable total.</p></article><article className="infra-card reveal"><span>ERC-7984</span><h3>Confidential settlement</h3><p>Owners receive encrypted token balances with permissioned decryption.</p></article></div></div><div className="contract-strip reveal"><span className="contract-title">Deployed on Sepolia</span>{contracts.map(([name,address]) => <a key={name} href={`https://sepolia.etherscan.io/address/${address}`} target="_blank" rel="noreferrer"><span>{name}</span><code>{address.slice(0,6)}…{address.slice(-4)}</code><Arrow /></a>)}</div></section>
      <section className="final-cta section-pad"><div className="cta-orb" aria-hidden><span>§</span></div><div className="reveal"><div className="section-kicker"><span>05</span> Start privately</div><h2>Build ownership<br/>people can trust.</h2><p>Create a confidential cap table, route revenue, and give every owner a private view of what is theirs.</p><Link href="/app" className="button button-primary">Open Scrip <Arrow /></Link></div></section>
    </main>
    <footer className="site-footer">
      <div className="footer-brand"><Logo/><p>Confidential ownership and revenue distribution for on-chain organizations.</p><span>Built on Ethereum · Powered by Nox</span></div>
      <div className="footer-column"><strong>Product</strong><a href="#how-it-works">How it works</a><a href="#privacy">Privacy</a><Link href="/app">Launch app</Link></div>
      <div className="footer-column"><strong>Resources</strong><a href="https://github.com/TheWeirdDee/scrip" target="_blank" rel="noreferrer">GitHub ↗</a><a href={`https://sepolia.etherscan.io/address/${SCRIP_DISTRIBUTOR_ADDRESS}`} target="_blank" rel="noreferrer">Etherscan ↗</a></div>
      <div className="footer-bottom"><span>© 2026 Scrip</span><span>Private ownership. Provable outcomes.</span></div>
    </footer>
  </div></LandingMotion>;
}
